// funtion() to get all the items in the list

function get_list(){
	var todo = new Array;
	var todo_str = localStorage.getItem('todo');
	if(todo_str != null){
		todo = JSON.parse(todo_str);
	}
	return todo;
}

// function() to add a new item to the list (localStorage)

function add(){
	var item = document.getElementById('task').value;
	var todo = get_list();
	todo.push(item);
	localStorage.setItem('todo', JSON.stringify(todo));

	show();

	document.getElementById('task').value = '';

	return false; // to avoid any further actions generated by 'click' event
}

// function() to show the items in HTML format

function show(){
	var list = get_list();

	var html = '<ul>';
	for(var i=0; i < list.length; i++){
		html += '<li>' + list[i] + '<button class="remove" id="' + i + '">x</button></li>';
	};

	document.getElementById('todos').innerHTML = html;

	var buttons = document.getElementsByClassName('remove');
	for(var i = 0; i<buttons.length; i++){
		buttons[i].addEventListener('click', remove);
	};
}

// function() to remove an item from the list

function remove(){
	var id = this.getAttribute('id');
	var list = get_list();
	list.splice(id, 1);
	localStorage.setItem('todo', JSON.stringify(list));

	show();

	return false;
}

document.getElementById('add').addEventListener('click', add);
show();